[package]
name = "nova-dso-tracker"
version = "1.3.0"
edition = "2024"
authors = ["Antongutscher"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
semver = "1"
tokio = { version = "1", features = ["process", "time", "rt"] }
ureq = "2"
dirs = "5"
